# fly.toml app configuration file generated for zigliki-hi-bot-staging on 2026-06-29T06:46:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zigliki-hi-bot-staging'
primary_region = 'yyz'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  builder = 'heroku/builder:24'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
